services:
  # -----------------------------
  # Service Base de données (Postgres)
  # -----------------------------
  postgres-witcher:
    image: postgres:16-alpine
    container_name: witcher-postgres
    environment:
      POSTGRES_DB: witcher_db
      POSTGRES_USER: witcher_user
      POSTGRES_PASSWORD: Team_Witcher_Dev!2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Le dossier pour vos scripts de création de schémas (optionnel si le dossier n'existe pas encore)
      - ./init-scripts:/docker-entrypoint-initdb.d 
    restart: unless-stopped

  # -----------------------------
  # Service Interface Graphique (pgAdmin)
  # -----------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: witcher-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@witcher.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      # CORRECTION ICI : Doit correspondre au nom du service ligne 5
      - postgres-witcher 

volumes:
  postgres_data:
